import type { User, Product, Order, Category } from "./types"

// Mock Users
export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "demo@example.com",
    password: "password", // In production, this would be hashed
    firstName: "Demo",
    lastName: "User",
    role: "admin",
    phone: "+1 (555) 123-4567",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
    addresses: [
      {
        id: "addr-1",
        userId: "user-1",
        type: "shipping",
        firstName: "Demo",
        lastName: "User",
        address1: "123 Main Street",
        city: "San Francisco",
        state: "CA",
        zipCode: "94105",
        country: "US",
        isDefault: true,
      },
    ],
  },
  {
    id: "user-2",
    email: "customer@example.com",
    password: "password",
    firstName: "Jane",
    lastName: "Smith",
    role: "customer",
    phone: "+1 (555) 987-6543",
    createdAt: "2024-02-01T14:30:00Z",
    updatedAt: "2024-02-01T14:30:00Z",
    addresses: [],
  },
]

// Mock Categories
export const mockCategories: Category[] = [
  {
    id: "cat-1",
    name: "Electronics",
    slug: "electronics",
    description: "Latest electronic devices and gadgets",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "cat-2",
    name: "Fashion",
    slug: "fashion",
    description: "Trendy clothing and accessories",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: "cat-3",
    name: "Home & Garden",
    slug: "home-garden",
    description: "Everything for your home and garden",
    sortOrder: 3,
    isActive: true,
  },
  {
    id: "cat-4",
    name: "Sports & Fitness",
    slug: "sports-fitness",
    description: "Sports equipment and fitness gear",
    sortOrder: 4,
    isActive: true,
  },
]

// Mock Products (expanded from the existing ones)
export const mockProducts: Product[] = [
  {
    id: "prod-1",
    name: "Premium Wireless Headphones",
    description:
      "High-quality wireless headphones with noise cancellation and premium sound quality. Perfect for music lovers and professionals.",
    price: 299.99,
    compareAtPrice: 399.99,
    category: "Electronics",
    subcategory: "Audio",
    brand: "AudioTech",
    sku: "AT-WH-001",
    inventory: 50,
    images: ["/premium-wireless-headphones.png"],
    tags: ["wireless", "noise-cancelling", "premium", "audio"],
    status: "active",
    featured: true,
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-10T09:00:00Z",
    variants: [
      {
        id: "var-1",
        productId: "prod-1",
        name: "Black",
        sku: "AT-WH-001-BLK",
        price: 299.99,
        inventory: 25,
        attributes: { color: "Black" },
      },
      {
        id: "var-2",
        productId: "prod-1",
        name: "White",
        sku: "AT-WH-001-WHT",
        price: 299.99,
        inventory: 25,
        attributes: { color: "White" },
      },
    ],
  },
  {
    id: "prod-2",
    name: "Smart Fitness Watch",
    description:
      "Advanced fitness tracking with heart rate monitoring, GPS, and smartphone connectivity. Track your health and fitness goals.",
    price: 249.99,
    category: "Electronics",
    subcategory: "Wearables",
    brand: "FitTech",
    sku: "FT-SW-002",
    inventory: 75,
    images: ["/smart-fitness-watch.png"],
    tags: ["fitness", "smartwatch", "health", "gps"],
    status: "active",
    featured: true,
    createdAt: "2024-01-12T11:00:00Z",
    updatedAt: "2024-01-12T11:00:00Z",
    variants: [
      {
        id: "var-3",
        productId: "prod-2",
        name: "Silver",
        sku: "FT-SW-002-SLV",
        price: 249.99,
        inventory: 40,
        attributes: { color: "Silver" },
      },
      {
        id: "var-4",
        productId: "prod-2",
        name: "Black",
        sku: "FT-SW-002-BLK",
        price: 249.99,
        inventory: 35,
        attributes: { color: "Black" },
      },
    ],
  },
  {
    id: "prod-3",
    name: "Organic Cotton T-Shirt",
    description: "Comfortable and sustainable organic cotton t-shirt. Perfect for everyday wear with a classic fit.",
    price: 29.99,
    category: "Fashion",
    subcategory: "Clothing",
    brand: "EcoWear",
    sku: "EW-TS-003",
    inventory: 100,
    images: ["/organic-cotton-tshirt.png"],
    tags: ["organic", "cotton", "sustainable", "casual"],
    status: "active",
    featured: false,
    createdAt: "2024-01-15T13:00:00Z",
    updatedAt: "2024-01-15T13:00:00Z",
    variants: [
      {
        id: "var-5",
        productId: "prod-3",
        name: "Small - White",
        sku: "EW-TS-003-S-WHT",
        price: 29.99,
        inventory: 20,
        attributes: { size: "S", color: "White" },
      },
      {
        id: "var-6",
        productId: "prod-3",
        name: "Medium - White",
        sku: "EW-TS-003-M-WHT",
        price: 29.99,
        inventory: 25,
        attributes: { size: "M", color: "White" },
      },
      {
        id: "var-7",
        productId: "prod-3",
        name: "Large - White",
        sku: "EW-TS-003-L-WHT",
        price: 29.99,
        inventory: 20,
        attributes: { size: "L", color: "White" },
      },
      {
        id: "var-8",
        productId: "prod-3",
        name: "Small - Black",
        sku: "EW-TS-003-S-BLK",
        price: 29.99,
        inventory: 15,
        attributes: { size: "S", color: "Black" },
      },
      {
        id: "var-9",
        productId: "prod-3",
        name: "Medium - Black",
        sku: "EW-TS-003-M-BLK",
        price: 29.99,
        inventory: 20,
        attributes: { size: "M", color: "Black" },
      },
    ],
  },
]

// Mock Orders
export const mockOrders: Order[] = [
  {
    id: "order-1",
    userId: "user-2",
    orderNumber: "ORD-2024-001",
    status: "delivered",
    items: [
      {
        id: "item-1",
        orderId: "order-1",
        productId: "prod-1",
        variantId: "var-1",
        quantity: 1,
        price: 299.99,
        total: 299.99,
        productSnapshot: {
          name: "Premium Wireless Headphones",
          image: "/premium-wireless-headphones.png",
          sku: "AT-WH-001-BLK",
        },
      },
    ],
    subtotal: 299.99,
    tax: 24.0,
    shipping: 9.99,
    total: 333.98,
    currency: "USD",
    shippingAddress: {
      id: "addr-2",
      userId: "user-2",
      type: "shipping",
      firstName: "Jane",
      lastName: "Smith",
      address1: "456 Oak Avenue",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90210",
      country: "US",
      isDefault: true,
    },
    billingAddress: {
      id: "addr-3",
      userId: "user-2",
      type: "billing",
      firstName: "Jane",
      lastName: "Smith",
      address1: "456 Oak Avenue",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90210",
      country: "US",
      isDefault: true,
    },
    paymentMethod: "Credit Card",
    paymentStatus: "paid",
    createdAt: "2024-02-01T15:00:00Z",
    updatedAt: "2024-02-05T10:00:00Z",
    shippedAt: "2024-02-02T09:00:00Z",
    deliveredAt: "2024-02-05T14:30:00Z",
  },
]
